baseURL = 'https://zeyasec.github.io/'
languageCode = 'en-us'
title = 'zeyasec'
theme = 'hugo-blog-awesome'

defaultContentLanguage = "en-us"

enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

[services]
  [services.googleAnalitics]
    id = ''

  [services.disqus]
    shortname = ''

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
    [markup.tableOfContents]
      startLevel = 2
      endLevel = 4
      ordered = false


[Languages.en-us]
  languageName = "English"
  languageCode = "en-us"
  contentDir = "content"
  weight = 1

  [Languages.en-us.menu]
  [[Languages.en-us.menu.main]]
    pageRef = "/"
    name = "Home"
    url = "/"
    weight = 10
  [[Languages.en-us.menu.main]]
    pageRef = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20
  [[Languages.en-us.menu.main]]
    pageRef = "about"
    name = "About"
    url = "/about/"
    weight = 30

[[params.socialIcons]]
name = "github"
url = "https://github.com/zeyasec"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/zeyasec"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"

[Languages.en-us.params]
  sitename = "zeyasec"
  goToTop = true
  description = "OSINT | Cyber Security | Digital Forensics | Software Engineer"
  mainSections = ['posts']
  toc = true
  tocOpen = false
  dateFormat = ""
  rssFeedDescription = "summary"

[Languages.en-us.params.author]
  avatar = "avatar.jpg"
  intro = "zeyasec"
  name = "zeyasec"
  description = "OSINT | Cyber Security | Digital Forensics | Software Engineer"

[Languages.en-us.params.webmanifest]
  name = "zeyasec"
  short_name = "zeyasec"
  start_url = "/"
  display = "standalone"
